version: '3.1'

services:

  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=20011002
      - MYSQL_HOST="127.0.0.1"
    ports:
      - "3307:3306"